### ISSUE TITLE
Question: Can I change the uischema after rendering?

### ISSUE THREAD

**Issue by kfitzvineti** [eclipsesource/jsonforms#1370]
I have a React model with a  uischema property which creates my jsonform. I would like to update the uischema with options dynamically. Currently when I do this, the form does re-render, but the value attributes all go away. Is this working as designed?

Thanks,
Kevin

**Comment by kfitzvineti** [comment]
My use case, btw, is using Storybook JS to display our components, many of which use jsonforms. 

It looks something like this, where the 'displayOnly' is dynamically updated.
```
          {
            "type": "DescribedGroup",
            "elements": [           
              {
                "type": "Control",
                "scope": "#/properties/shipping_receipt_checklist/properties/shipper_seal_intact_question",
                "options": {
                  "renderer": "textAndToggle",
                  "displayOnly": ${displayOnly}
                }
              }
            ]
          }
```

**Comment by edgarmueller** [comment]
How are you updating the UI schema? If you update via the `Actions.setUISchema` and pass in your updated root UI schema this should work.

**Comment by kfitzvineti** [comment]
I was naïvely rewriting the JS literal that's passed as a property to my wrapper component. I'll check out `setUISchema`.

**Comment by edgarmueller** [comment]
I'm closing this now as the question seems to have been answered.

**Comment by wimueller** [comment]
Could you please explain how to call `Actions.setUISchema` in React. When passing a `uischema` stored in a variable my JsonForms component is not rerendering. Thank you in advance!

**Comment by sdirix** [comment]
> Could you please explain how to call `Actions.setUISchema` in React. When passing a `uischema` stored in a variable, my JsonForms component is not rerendering. Thank you in advance!

@wimueller Since we removed Redux support these actions are no longer dispatchable from outside of JSON Forms. In fact `JsonForms` now behaves like a regular React component. All you need to do to rerender JSON Forms with a different ui schema is to pass a different ui schema prop. If this doesn't work for you, please post your example either in our [community board](https://spectrum.chat/jsonforms) or [open a bug report](https://github.com/eclipsesource/jsonforms/issues/new/choose).
