### ISSUE TITLE
Question: ASP.net MVC Core Usage

### ISSUE THREAD

**Issue by learner291** [eclipsesource/jsonforms#1538]
Hi,

Can we use jsonforms in our ASP.net mvc core web application? We use Razor and Jquery on the client side.

Thanks

**Comment by sdirix** [comment]
JSON Forms is just a regular Javascript library, so it can definitely be integrated. You might want to take a look at the [Microsoft React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-3.1&tabs=visual-studio) and the [JSON Forms React seed](https://github.com/eclipsesource/jsonforms-react-seed) to get started quickly.

**Comment by learner291** [comment]
Thanks, I have got two more questions:
1) Will just a basic React knowledge fine in order to work with JSON forms as I would like to use the library in asp.net mvc core?
2) In one of your examples on your website, Enum Nationality is used with text values. In our application, we have a lookup table for Nationality and we store Id from the lookup table into our Person table so my question is, is there a mechanism in JSON forms library to map text in Enum to relevant Ids?

**Comment by sdirix** [comment]
> 1. Will just a basic React knowledge fine in order to work with JSON forms as I would like to use the library in asp.net mvc core?

This depends on your use case. If the provided renderers cover everything you need, then you only need minimal React knowledge. Once you want to implement an own renderer for example to customize a field with very specific business logic, you'll need to implement it using React.

Note that we also offer Angular renderers, so if you're more familiar with Angular than React you could also use them.

> 2. In one of your examples on your website, Enum Nationality is used with text values. In our application, we have a lookup table for Nationality and we store Id from the lookup table into our Person table so my question is, is there a mechanism in JSON forms library to map text in Enum to relevant Ids?

The problem here is that JSON Schema doesn't support non-text enums. There are two ways how you could map the text to id:

1. You can build your own enum structure using `oneOf` like outlined in this [Spectrum question](https://spectrum.chat/jsonforms/general/for-enums-i-need-to-be-able-to-put-labels-for-the-enum-values~5b8b5153-033f-43a9-8f5e-bc27c37a2781). However to get a reasonable UI you'll then need to implement a custom renderer as we don't offer such a renderer for this special case yet. The advantage of this solution is that the mapping information is then placed in the schema and could also be used by other tools.
2. You can just implement a custom renderer from the get go and do whatever you would like. For example the schema could just reflect the ids from your "real" data schema, however the renderer will still show the result of looking up the id in the person table.

Either way you'll need to implement a custom renderer for now if you don't want the user to manipulate the ids instead of texts. Id you'd like to contribute the renderer outlined in option 1 we'll definitely support you in doing so.

**Comment by learner291** [comment]
Thanks

**Comment by sdirix** [comment]
https://json-schema.org/implementations.htmlhas a good overview of available frameworks covering one or more JSON Schema use cases for different languages and environments. For UI Schemas you can either rely on the auto generation of JSON Forms, use the exported generator utilities or implement a generator yourself.
