### ISSUE TITLE
Rendering Issue with Material UI for JsonForms using React and Redux

### ISSUE THREAD

**Issue by kgrvamsi** [eclipsesource/jsonforms#1541]
**Describe the bug**
Was trying to render the material ui based rendering but i see the following issue.

code snippet for the following implementation

```
export default ({ children }) => {
  let jsonFormsState = {
    jsonforms: {
      cells: materialCells,
      renderers: materialRenderers
    }
  };
  const store = createStore(
    combineReducers({ jsonforms: jsonformsReducer(), reducers }),
    jsonFormsState,
    composeEnhancers(applyMiddleware(...middlewares))
  );

  return (
    <Provider store={store}>
      <JsonFormsReduxContext>{children}</JsonFormsReduxContext>
    </Provider>
  );
};
```

**To Reproduce**

**Expected behavior**
Expecting to take the material renders instead declaring in the json form.

code snippet for json forms rendering

```
return (
    <Card className={clsx(classes.root, className)}>
      <CardHeader title="Form" />
      <Divider />
      <CardContent>
        <JsonForms
          schema={props.schema}
          uischema={props.uiSchema}
          data={standaloneData}
          onChange={({ errors, data }) => setStandaloneData(data)}
        />
      </CardContent>
      <Divider />
      <CardActions>
        <Button
          color="primary"
          variant="outlined"
        >
          <AddIcon /> Add 
        </Button>
      </CardActions>
    </Card>
  );
};
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1199031/74080254-c21b0a80-4a07-11ea-9519-8a40755d49e3.png)

**Browser (please complete the following information):**
 - Browser Chrome

**Used Setup (please complete the following information):**
 - Framework: React with Hooks
 - RendererSet: Material

**Comment by sdirix** [comment]
Hi @kgrvamsi, thanks for the detailed problem description!

When using the Redux variant of JSON Forms you need to use `<JsonFormsDispatch />` instead of `<JsonForms/>` to render JSON Forms. `<JsonForms/>` is the component to use when you don't want to use Redux. You can see both variants in our [JSON Forms React seed](https://github.com/eclipsesource/jsonforms-react-seed/blob/1861db6102f41cd668068d4ad8ac2c5c1a0bc5be/src/App.tsx).

Can you try whether that solves the problem for you? If not, could you provide an executable example so we can more easily take a look at the problem?

Note that we are currently working on removing [Redux from JSON Forms](https://github.com/eclipsesource/jsonforms/issues/1537), so you might want to switch to the standalone `<JsonForms />` variant in general, although it'll take a while until we completely remove it. When using the standalone variant you have to specify the renderers and cells as props in the `<JsonForms />` component. For more information you can also check our [FAQ](https://jsonforms.io/faq)

I hope this is helpful to you ;)

**Comment by sdirix** [comment]
I'll close this for now. Please re-open if you have any more problems or questions regarding this issue.
