### ISSUE TITLE
Replace TSLint with ESLint and Prettier

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#1551]
TSLint is officially deprecated. Move to ESLint + Prettier: https://prettier.io/docs/en/integrating-with-linters.html

**Comment by lucas-koehler** [comment]
- Integrate Prettier in ESLint so that prettier formatting is applied on linting.
- For prettier:
  - use single quotes
  - use line ending auto to be compatible with Windows development using default Git settings.
- Prefer rule recommendations over explicitly configuring many.
- Consider making the packages' configs self-contained in each package as long as there is not too much duplication

**Comment by lucas-koehler** [comment]
Fixed via #2112 . Follow up tasks tracked in #2131
