### ISSUE TITLE
Error occurred when using in real angular project.

### ISSUE THREAD

**Issue by tk2dev90** [eclipsesource/jsonforms#1571]
I got errors when I tried to use with real angular project.
I used `@jsonforms/core` and `@jsonforms/angular`.
When I run the application with `ng serve`, I can see following errors.

```
ERROR in ./node_modules/json-schema-ref-parser/lib/resolvers/http.js
Module not found: Error: Can't resolve 'http' in '<path-of-project>\node_modules\json-schema-ref-parser\lib\resolvers'
ERROR in ./node_modules/json-schema-ref-parser/lib/resolvers/http.js
Module not found: Error: Can't resolve 'https' in '<path-of-project>\node_modules\json-schema-ref-parser\lib\resolvers'
```

**To Reproduce**
```
# create angular project
ng new my-project

# install @jsonforms dependencies
npm i @jsonforms/core@^2.4.0-alpha.2 @jsonforms/angular@^2.4.0-alpha.2 redux

# import `JsonFormsModule` to some angular module then run project with `ng serve`
ng serve
```

**Expected behavior**
The Angular application started without any errors.

**Used Setup (please complete the following information):**
 - Framework: Angular
 - RendererSet: 

**Additional context**
My `tsconfig.json` is here.
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "allowSyntheticDefaultImports": true,
    "enableIvy": false
  }
}
```

This is my `tsconfig.app.json`.
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": ["node"]
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```

I hope I can find way to solve this problem from here!
Thanks.

**Comment by eneufeld** [comment]
Hi @tk2dev90 ,
sorry for the late reply.
In order to fix this error you need to add:
`
"browser": {
    "http": false,
    "https": false
  }
`
to the `package.json`.
As far as I can see in your description you might be missing the `@jsonforms/angular-material` package.
For an Angular 9 application you can check: https://github.com/eclipsesource/jsonforms-angular-material-playground/pull/34 . 
Because Jsonforms 2.4.0 is not yet release we didn't merge this PR.

Please let us know whether this solves your issues.
Best,
Eugen

**Comment by sdirix** [comment]
Close this for now as there was no more feedback.

**Comment by sookoll** [comment]
I bump this up. About this project: Great idea, awful implementation. No vanilla renderers? If I do not want material forms on angular project, what then? No documentation how to create custom renderers for simple native html forms. Why the hell I need redux installed?

**Comment by sdirix** [comment]
Hi @sookoll thanks for your feedback and suggestions.

JSON Forms is build in a modular way, so when a renderer or renderer set is missing for your use case you can implement it yourself. For an Angular Vanilla renderer set you can even reuse the generic Angular bindings (`@jsonforms/angular`). If you'd like you could then contribute it back.

There is not much documentation for the Angular renderers specifically, however you can check the [JSON Forms Angular seed](https://github.com/eclipsesource/jsonforms-angular-seed) for reference. The JSON Forms website is also [open source](https://github.com/eclipsesource/jsonforms2-website) so we would be happily accepting documentation. 

JSON Forms was originally Redux-based. We're in the process of removing Redux from JSON Forms but it's not yet completed, however we're working on it and we expect to be completely Redux free with one of the next versions.

**Comment by sookoll** [comment]
Thanks for replay. I played with this angular seed. I got my own JSONSchema to work (do I have to create one-to-one UISchema? Shouldn't this work also without UISchema?) with it. I also see, that there is custom autocomplete renderer. However, this extends material autocomplete, not generic Angular bindings. Also, module code looks awfully complex. Why it not work with just importing needed modules in module and schemas + data in component/template? I'm currently on decision, should I stay with jsonforms or move on to Formly, which is clean and nice Angular project.

**Comment by eneufeld** [comment]
Hi @sookoll , 

- `do I have to create one-to-one UISchema?` No you can omit the UISchema and it will be auto generated for you. Probably you will want to provide one at some point to improve the layout.
- `However, this extends material autocomplete, not generic Angular bindings` Every JSONForms Renderer is an Angular component. So if you want to write an autocomplete renderer without reusing material, you can do so. 
- `Also, module code looks awfully complex` The code in the module configures ajv (no need to do so if the default is enough for you) loads the predefined uischema and schema (no need to use promises if you can access them otherwise) and the relevant code is initializing the app. 
So to renderer jsonforms assuming you have a schema and data ready to use looks like this:
```
export class AppModule {
  constructor(jsonformsService: JsonFormsAngularService) {

    jsonformsService.init({
        renderers: angularMaterialRenderers
    });
    ...
  }
}
```
Your component can then look like this:
```
@Component({
  selector: 'app-root',
  template: `
    <h1>Angular Material Examples</h1>
    <jsonforms-outlet></jsonforms-outlet>
  `
})
export class AppComponent {
  constructor(private jsonformService: JsonFormsAngularService) {
    this.jsonformService.updateCore(
      Actions.init(
        data,
        schema
      )
    );
```
As @sdirix wrote we are in the process of getting rid of Redux. The use of the `JsonFormsAngularService` is a remnant of the explicit redux use. We are happy to accept contributions that improve the framework.
