### ISSUE TITLE
Disable rule on group does not disable contents.

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/jsonforms#1586]
**Describe the bug**
Using a UI schema rule to disable a group does not disable the group's contained controls.

**To Reproduce**
1. Create UI Schema with a group containing at least one control.
2. Add disable rule to the group
3. Trigger the rule and check the control's state
4. The control can still be edited

**Expected behavior**
The control should be disabled

**Screenshots**

**Browser (please complete the following information):**

**Used Setup (please complete the following information):**
 - Framework: react
 - RendererSet: vanilla

**Additional notes**
Possibly the same problem also applies to other layout renderers and/or hide rules.

**Comment by sdirix** [comment]
The problem here is that `GroupLayoutRenderer` should hand over its `enabled` prop to its children but doesn't do so. As we still use the `cells` system in the Vanilla renderers for all inputs we should also check all other `visible` and `enabled` props of all Vanilla renderers to hand them over appropriately.
