### ISSUE TITLE
How to define custom renderer

### ISSUE THREAD

**Issue by luxer066** [eclipsesource/jsonforms#1595]
Hi. I have problem to configure tester for my custom render. 
I need to create for address.addressname and address.city
```javascript
const PersonSchema = {
  type: 'object',
  properties: {
    person: {
      type: 'array',
      title: 'Person',
      items: {
        type: 'object',
        properties: {
          name: {
            type: 'string',
            title: 'Name',
          },
          address: {
            type: 'array',
            title: 'Address',
            items: {
              type: 'object',
              properties: {
                addressname: {
                  type: 'string',
                },
                city: {
                  type: 'string',
                },
              },
            },
          },
        },
      },
    },
  },
};
export default PersonSchema
```
****************************************************************************
```javascript
const PersonUISchema = {
  type: "HorizontalLayout",
  elements: [
    {
      type: "Control",
      scope: "#/properties/person",
    },
  ],
}
export default PersonUISchema
```
****************************************************************************
```javascript
storePerson.dispatch(
  Actions.registerRenderer(AddressNameTester,AddressName),
) 
storePerson.dispatch(
  Actions.registerRenderer(AddressCityTester,AddressCity),
)
```
****************************************************************************
```javascript
export const AddressNameTester: RankedTester = rankWith(
  3,
  scopeEndsWith("addressname"),
)

export const AddressCityTester: RankedTester = rankWith(
  3,
  scopeEndsWith("city"),
)
```

****************************************************************************

**Comment by sdirix** [comment]
Hi @luxer066, thanks for your question!

In JSON Forms we distinguish between `renderers` and `cells`. Both are responsible for rendering, however `cells` are specialized for tables, while `renderers` handle all other use cases. We distinguish them because usually an input is rendered completely different within table compared to being a normal part of the form.

In your example `address` is an `array` of a shallow `object` without an additional ui schema for the array. In this case we use the table renderer, where each of the object property becomes a column. There are two ways to solve the issue:
 1. Customize the table cells
 2. Don't use the table renderer

#### 1. Customizing table cells
When you want to customize the table, you need to register `cell` instead of `renderer`. Therefore your code should look like this:
```javascript
storePerson.dispatch(Actions.registerCell(AddressNameTester, AddressName));
storePerson.dispatch(Actions.registerCell(AddressCityTester, AddressCity));
```
Note that cells have a slightly different API than renderers, so you might need to adjust your `AddressName` and `AddressCity` a bit.

#### 2. Use non-table renderer
If you prefer to use the non-table variant you don't need to change your code at all but could adapt the ui schema to not use the table renderer. For example like this:
```json
{
  "type": "HorizontalLayout",
  "elements": [
    {
      "type": "Control",
      "scope": "#/properties/person",
      "options": {
        "detail": {
          "type": "VerticalLayout",
          "elements": [
            { "type": "Control", "scope": "#/properties/name" },
            {
              "type": "Control",
              "scope": "#/properties/address",
              "options": {
                "detail": "Generated"
              }
            }
          ]
        }
      }
    }
  ]
}
```
---

Side Note:
The distinction between `cells` and `renderers` is not yet there for the Vanilla renderers. There the 
`renderers` depend on the `cells` to render their content. This will be refactored at some point.

---

I see that you are using the Redux variant of JSON Forms. We are currently working hard on removing the Redux dependency from JSON Forms. So if you would prefer not using Redux you can already use the Standalone version of JSON Forms. See [jsonforms.io](https://jsonforms.io/faq#how-can-i-listen-to-form-changes-in-the-react-standalone-component) for more information.

**Comment by luxer066** [comment]
Hi @sdirix 

When I start using JsonForm I use Standalone and then switch to the Redux version of JSON Forms following the React Seed example.

Are you going to remove redux to use useReducer or why do you recommend using Standalone Version of JSON Forms?

Returning to the question, excellent answer! Very detailed everything. Solved my problem. 
Thanks for answering. Greetings from Argentina.

**Comment by sdirix** [comment]
> When I start using JsonForm I use Standalone and then switch to the Redux version of JSON Forms following the React Seed example.

The react seed showcases both approaches: Redux and Standalone.

> Are you going to remove redux to use useReducer or why do you recommend using Standalone Version of JSON Forms?

Yes the Redux variant will be removed at some point as we no longer require Redux's feature set and a lot of user would like to opt out of Redux. Internally we already moved most of the code to use React's context instead. At the moment we're polishing the Standalone version until we hit feature parity with Redux which is not too far off. Of course we'll provide an easy way out for all existing Redux users, however I recommend using Standalone wherever possible to ease the migration later on.

> Returning to the question, excellent answer! Very detailed everything. Solved my problem.
Thanks for answering. Greetings from Argentina.

Glad to help :) Whenever you have a question you can also check our [Spectrum community](https://spectrum.chat/jsonforms?tab=posts).
