### ISSUE TITLE
Populate enum dynamically

### ISSUE THREAD

**Issue by piyush0609** [eclipsesource/jsonforms#1622]
**Describe the bug**
There is a string field for which enum has to be populated dynamically. For eg.

My json schema looks like this
```
{
  "loadBalancers": {
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "endpoint": {"type": "string"},
        "name": {
          "type": "string",
          "description": "To distinguish between multiple load balancers of same type"
        }
      }
    }
  },
  "securityGroup": {
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "endpoint": {
          "type": "string"
        },
        "vpcId": {
          "type": "string"
        }
      }
    }
  }
}
```
The field `securityGroup` has sub field `endpoint` which can be an enum and can have the values of `loadBalancers -> endpoint`. Since loadBalancer is an array I will be able to get a list of `endpoint` and give the user an option to a select.

Basically i want to populate an enum using the values of a different field.

How can i solve this use case?

**Expected behavior**
Populate enums dynamically

**Browser (please complete the following information):**
 - Browser [e.g. chrome]
 - Version [e.g. 83]

**Used Setup (please complete the following information):**
 - Framework: [e.g. react]
 - RendererSet: [e.g. material]

**Comment by sdirix** [comment]
Hi @piyush0609, I see two different approaches:
 * You could adapt your JSON Schema dynamically. So whenever you know the content of the `loadBalancers` change, you could also adapt the JSON Schema given to JSON Forms and declare all allowed enum values of `securityGroup > endpoint`. 
 * Alternatively you can register a custom renderer for `securityGroup > endpoint`. Within the custom renderer you can just reuse our `MaterialEnumControl` or `MaterialAutocompleteEnumControl` and hand in the `options` (i.e. valid enum values) yourself by looking at the `loadBalancers > endpoint` properties.

Depending on your use case you might prefer one of the two approaches. When using the custom renderer approach you could implement it (and potentially its tester) in a generalized way so that whenever you need this 'dynamic enum' it either works out of the box (matching property names) or at least is easily configured declaratively in the ui schema.

**Comment by sdirix** [comment]
I'll close this issue for now. Please reopen or ask in [Spectrum](https://spectrum.chat/jsonforms) when you have further questions.
