### ISSUE TITLE
Users can specify UI options for generated react ui

### ISSUE THREAD

**Issue by silencej** [eclipsesource/jsonforms#1674]
Auto-generated ui schema is very convinient and good for user's code maintainence.

However, in order to specify some string input as textarea, the users have to specify manually in the ui schema { option: 'multiline' }. 

It will be good if the generator supports the ui option.
The solution could be to specify the option in model definition, or have a "multilineString" like type.

**Comment by sdirix** [comment]
Hi @silencej, I can understand the use case but I'm not sure that enhancing the ui schema generator is the best way to go. There are many ways one could adapt the ui schema generator and customizing only for multiline text fields feels out of place.

If you want a specific ui schema I think it makes the most sense when you write a specialized ui schema generator fitting for your needs. [The generator code is not that much, so you could just copy it](https://github.com/eclipsesource/jsonforms/blob/612a38acb8f55afedc95e74299eb0a7a7e64fd6c/packages/core/src/generators/uischema.ts).

If you only want to slightly modify the ui schema you can invoke the existing generator and adapt its result like this:

```ts
import { Generate } from '@jsonforms/core';
const uiSchema = Generate.uiSchema(schema);
```

Other alternatives:
 * Specify `multi: true` in the config object. This will lead to *ALL* texts being multiline
 * Implement a custom text renderer which always renders inputs as text areas and tune the tester so that it applies only to the fields you intend to be multiline. The implementation is straightforward as you mainly need to delegate to the existing text renderer but manually specify the multi option.
