### ISSUE TITLE
Old values are send when there arre errors

### ISSUE THREAD

**Issue by DavidHenri008** [eclipsesource/jsonforms#1678]
The state passed to the onChange callback is the previous value when there are errors.
This has a weird infinite loop effect due to desynchronized values.

If there are no schema errors there is no issue.

Run the following [codesandbox ](https://codesandbox.io/s/json-formsonchange-old-values-6c33u?file=/src/index.js) in order to view the issue.
Simply click the Toggle Schema and look at the console to view the data order.

jsonForms version 2.5.0-alpha1

**Comment by sdirix** [comment]
Hi @DavidHenri008, good find! We'll take a look soon!

**Comment by sdirix** [comment]
Hi @DavidHenri008, I analyzed the problem. The issue is actually in the example code and not related to JSON Forms itself.

As a reminder, this is the app code:
```js
function App() {
  const [data, setData] = useState({ name: "John", age: "t" });
  const [schemas, setSchemas] = useState({ schema, uiSchema });

  const onChange = (state) => {
    console.log("onchange", state.data, state.errors, schemas.schema);
    setData(state.data);
  };

  const changeSchema = (state) => {
    if (data.name) {
      setSchemas({ schema: schema2, uiSchema: uiSchema2 });
    } else {
      setSchemas({ schema: schema, uiSchema: uiSchema });
    }
  };

  useEffect(() => {
    console.log("uE setData");
    setData((current) => {
      if (schemas.schema.properties.name) {
        return { name: "John", age: "t" };
      } else {
        return { city: "Montreal", year: 2019 };
      }
    });
  }, [schemas]);

  console.log("render", data, schemas);

  return (
    <div className="App">
      <JsonForms
        data={data}
        schema={schemas.schema}
        uischema={schemas.uiSchema}
        renderers={materialRenderers}
        onChange={onChange}
      />
      <button onClick={changeSchema}>Toggle schema</button>
    </div>
  );
}
```

The problem here is that the `useEffect` is executed asynchronously and therefore leads to an additional change event the code is not ready to handle.

1. User clicks on `Toogle schema`
2. The new schemas (`{schema2, uiSchema2}` are set), this triggers a re-rendering of the `App`

Next render pass:

1. The `useEffect` is queued to be executed because the `schemas` state changed. Note that `useEffect` is async and is executed at some point after the render pass.
2. JSON Forms is rendered with the new `schemas` but with the old data
3. JSON Forms dispatches a change event containing the old data but with new errors as `data` and `schema` don't fit

Inbetween renderings
1. The queued `useEffect` is executed, setting a *new* data object which fits to `schema2, uischema2`. Setting a new `data` marks the App for rerendering

Next render pass:
1. JSON Forms is rendered with the fitting new data object and schema2, uischema2. Json Forms dispatches a change event containing the new data and schema2, uischema2

Inbetween renderings:
1. The first queued change event is executed, setting the `data` back to the old data. This marks the App for rerendering

Next render pass: 
1. JSON Forms is rendered with the old data object and the non-fitting schema2, uischema2. Json Forms dispatches a change event containing the new old data and schema2, uischema2

Inbetween renderings:
1. The second change event is executed, setting the data back to the new data. This marks the App for rerendering

etc. etc.

Advice: In general you should never chain-update state variables within the same component via `useEffect`. At best it leads to unnecessary rerenderings (original rendering and `useEffect + setState` rerendering), at worst you'll get infinite rerenderings when the affected state variables again trigger a `useEffect + setState` combination.

So to fix the problem you should just change all state variables at the same time. This avoids problems like this and also makes the code more readable as all "combined" state changes are located in the same place in the code, i.e.

```js
function App() {
  const [data, setData] = useState({ name: "John", age: "t" });
  const [schemas, setSchemas] = useState({ schema, uiSchema });

  const onChange = (state) => {
    console.log("onchange", state.data, state.errors, schemas.schema);
    setData(state.data);
  };

  const changeSchema = (state) => {
    if (data.name) {
      setSchemas({ schema: schema2, uiSchema: uiSchema2 });
      setData({ city: "Montreal", year: 2019 });
    } else {
      setSchemas({ schema: schema, uiSchema: uiSchema });
      setData({ name: "John", age: "t" });
    }
  };

  console.log("render", data, schemas);

  return (
    <div className="App">
      <JsonForms
        data={data}
        schema={schemas.schema}
        uischema={schemas.uiSchema}
        renderers={materialRenderers}
        onChange={onChange}
      />
      <button onClick={changeSchema}>Toggle schema</button>
    </div>
  );
}
```

**Comment by DavidHenri008** [comment]
It is true that synchronizing the schema and the data change in a single useEffect fix the issue. 
However, even with asynchronous code, like the original, the infinite loop issue happens only when there is at least one error in the schema. If you fix the age default value to a valid number you will see the loop going away...
Which makes me think the errors are causing a delay and make the onChange function sending the old values.
I do not understand how the following sequence occurs:
- render of JsonForms with Data1 and Schema1
- call of onChange with Data1
- render of JsonForms with Data1 and Schema2
- render of JsonForms with Data2 and Schema2
- call of onChange with Data1 ---> This seems illogical for me...

Thank you.

**Comment by sdirix** [comment]
Yes the problem does not occur when there are no validation errors at all , because the first JSON Forms rerender will not produce an event.

I cleaned up the log and added some additional messages, without changing the structure of the code.

This is the log with validation errors
```
set schema:  city
render data: John, schema: city
JSON Forms: Received new props -> internal rerender and potential dispatch emitting
uE setData:  Montreal
render data: Montreal, schema: city
JSON Forms: Dispatch event because of new data or new errors
onchange received and sets new data: John
render data: John, schema: city
JSON Forms: Received new props -> internal rerender and potential dispatch emitting
JSON Forms: Dispatch event because of new data or new errors
onchange received and sets new data: Montreal
render data: Montreal, schema: city
JSON Forms: Received new props -> internal rerender and potential dispatch emitting
JsonFormsContext.tsx:155 JSON Forms: Dispatch event because of new data or new errors
onchange received and sets new data: John
render data: John, schema: city
JSON Forms: Received new props -> internal rerender and potential dispatch emitting
JSON Forms: Dispatch event because of new data or new errors
onchange received and sets new data: Montreal
render data: Montreal, schema: city
...
```

This is the log without validation errors
```
set schema:  city
render data: John, schema: city
JSON Forms: Received new props -> internal rerender and potential dispatch emitting
uE setData:  Montreal
render data: Montreal, schema: city
JSON Forms: Received new props -> internal rerender and potential dispatch emitting
JSON Forms: Dispatch event because of new data or new errors
onchange received and sets new data: Montreal
```

The key difference is marked in **bold**

| With validation errors  | Without validation errors |
| ------------- | ------------- |
| set schema:  city  | set schema:  city  |
| render data: John, schema: city  | render data: John, schema: city  |
| **JSON Forms: Received new props -> internal rerender and potential dispatch emitting** | **JSON Forms: Received new props -> internal rerender and potential dispatch emitting** |
| uE setData:  Montreal | uE setData:  Montreal |
| render data: Montreal, schema: city | render data: Montreal, schema: city |
| **JSON Forms: Dispatch event because of new data or new errors** | **JSON Forms: Received new props -> internal rerender and potential dispatch emitting** |
| onchange received and sets new data: John | **JSON Forms: Dispatch event because of new data or new errors** |
| render data: John, schema: city | onchange received and sets new data: Montreal |
| **JSON Forms: Received new props -> internal rerender and potential dispatch emitting** | |
| **JSON Forms: Dispatch event because of new data or new errors** | |
| ... | |

Whenever JSON Forms receives new props it has the potential to generate an output event. It will produce one when there are data or validation changes.

On the left hand side (with validation errors) the first rendering of JSON Forms where only the `schema` changed will produce an event as JSON Forms calculated new validation errors. On the right hand side without validation errors the first rendering of JSON Forms will NOT produce the event as neither the data nor the validation (still no errors) changed. Therefore it will not enter the endless rerendering loop.

Now we could change that JSON Forms emits a change event no matter what, as one could argue that technically the validation is not the same, rather it is a *new* determination of there being no validation errors. However I don't see any benefits from that.

**Comment by DavidHenri008** [comment]
I see. I would not trigger more onChange events since this is what the new 2.5.0-alpha1 seems to fix.

Long story in short: it is highly recommended to synchronize properties changes and avoid chaining updates. This is true for any component and it is not related to JsonFoms implementation.

Thank you very much for your thorough analysis and quick response.
