### ISSUE TITLE
RTL support in Controls

### ISSUE THREAD

**Issue by mhashim6** [eclipsesource/jsonforms#1770]
### Is your feature request related to a problem? Please describe.

By default, all controls and labels assume LTR text, while we can fix some labels by applying `direction='rtl'` in the container tag, but the controls themselves have no config option (at least in material-renderers).

Thanks!

### Describe the solution you'd like

A way to configure controls to display in RTL direction, for languages like arabic. 

### Describe alternatives you've considered

Applying to `direction='rtl'` to the container tag/component. But it only works on `Label`s, not in `Control`s.

### Framework

- [X] Core
- [X] React
- [ ] Angular
- [ ] Vue 3
- [ ] Vue 2
- [ ] Other (please specify in the Additional context field)

### RendererSet

- [X] Material
- [ ] Vanilla
- [ ] Other (please specify in the Additional context field)

**Comment by sdirix** [comment]
Hi @mhashim6, thanks for the report. Did you try to follow [this guide](https://material-ui.com/guides/right-to-left/) of the Material UI team? Is there something missing in JSON Forms to support RTL text and inputs?

**Comment by mhashim6** [comment]
> Hi @mhashim6, thanks for the report. Did you try to follow [this guide](https://material-ui.com/guides/right-to-left/) of the Material UI team? Is there something missing in JSON Forms to support RTL text and inputs?

Hi @sdirix, in order to apply this guide I'll have to customize each control in the material renderers by wrapping them by the `LTR` component for example. 

I'd think a better way to do it is to use the aforementioned `RTL` component in JSON-Forms material renderers and have a flag for rtl support that will render the `control` wrapped with the `RTL` component.

I'd love to do it myself, but due to some circumstances I have very limited access to my computer.

**Comment by sdirix** [comment]
> > Hi @mhashim6, thanks for the report. Did you try to follow [this guide](https://material-ui.com/guides/right-to-left/) of the Material UI team? Is there something missing in JSON Forms to support RTL text and inputs?
> 
> Hi @sdirix, in order to apply this guide I'll have to customize each control in the material renderers by wrapping them by the `LTR` component for example.
> 
> I'd think a better way to do it is to use the aforementioned `RTL` component in JSON-Forms material renderers and have a flag for rtl support that will render the `control` wrapped with the `RTL` component.
> 
> I'd love to do it myself, but due to some circumstances I have very limited access to my computer.

If I read that guide correctly then the showcases `RTL` component influences ALL of its children, not only the ones directly contained in it. Also that is the only way it makes sense as otherwise customizing the theme would be pointless. So it's enough to set this up once, then wrap JSON Forms, or rather your whole application, with this component and then you should be fine.

In fact you can see this approach on their own website: [setup](https://github.com/mui-org/material-ui-docs/blob/feaad0a17e760fcfe6196aa351f25560346652c9/docs/pages/_app.js#L340-L342) and [switch](https://github.com/mui-org/material-ui-docs/blob/feaad0a17e760fcfe6196aa351f25560346652c9/docs/src/modules/components/AppFrame.js#L179-L181).

Doing this most of JSON Forms should be rendering RTL already. However there are probably some renderers where just flipping all Material UI components is not enough and JSON Forms should also behave differently. For example the Input clear button should be rendered on the left hand side then. For this JSON Forms should check the current theme for the direction, see for example [here](https://github.com/mui-org/material-ui-docs/blob/feaad0a17e760fcfe6196aa351f25560346652c9/docs/src/pages/components/drawers/ResponsiveDrawer.js#L116).

So the next steps are:
 - Identify all renderers in which JSON Forms RTL support is lacking
 - Fix them by checking the theme and render accordingly

**Comment by mhashim6** [comment]
Thank you, @sdirix, I'll test as soon as I can, and I'll come back to you.

**Comment by mhashim6** [comment]
Hi, @sdirix , this approach worked perfectly, thanks!
