### ISSUE TITLE
Conditional subschema's not accesible

### ISSUE THREAD

**Issue by jessevdp** [eclipsesource/jsonforms#1772]
### Describe the bug

JSON Schema has support for [conditional subschemas](https://json-schema.org/understanding-json-schema/reference/conditionals.html). I'm building a custom renderer set that needs to be able to handle schema's with these types of conditional subschema's in them.

Take the following schema for example:

```json
{
    "type" : "object",
    "properties" : {
      "foo" : {
        "type" : "object",
        "properties" : {
          "my-condition" : {
            "type" : "boolean"
          },
          "my-conditional" : {
            "type" : "number"
          }
        },
        "required" : [ ]
      }
    },
    "allOf" : [ {
      "if" : {
        "properties" : {
          "foo" : {
            "properties" : {
              "my-condition" : {
                "const" : true
              }
            }
          }        }
      },
      "then" : {
        "properties" : {
          "foo" : {
            "properties" : {
              "my-conditional" : {
                "minimum" : 1.0,
                "maximum" : 10.0,
                "multipleOf" : 0.5
              }
            },
            "required" : [ "my-conditional" ]
          }
        }
      }
    } ]
  }
```

This schema describes a data structure where, if the property `foo.my-condition` is set to true, the property `foo.my-conditional` becomes required and is validated as a number between 1 and 10 and is a multiple of 0.5.

In my number control renderer I have the following logic to retrieve these types of additional validation properties. I then bind these to the actual HTML `<input>` element so the browser can handle the stepper buttons.

(My custom renderer is written in Angular. I believe this code is not unlike the angular-material renderer example.)

```ts
  mapAdditionalProps(props: StatePropsOfControl) {
    if (this.scopedSchema) {
      const defaultStep = isNumberControl(this.uischema, this.rootSchema) ? 0.1 : 1;
      this.min = this.scopedSchema.minimum;
      this.max = this.scopedSchema.maximum;
      this.multipleOf = this.scopedSchema.multipleOf || defaultStep;
      
      // Some code omitted for brevity
    }
  }
```

It seems as though `scopedSchema` always contains the base declaration of the schema for the `foo.my-conditional` property:

```json
{
"type" : "number"
}
```

Is there any way to get the "real" schema as used by JSON schema to validate the data.

**To be clear, the validation works correctly.** I get all the errors I expect at the times that I expect them. I'm just not able to enhance the UX of my components with (in this case) stepper buttons that increment the correct amount and stop at min/max.

The same type of issue arrises for other renderers too. Numeric input is just an easy example.

---

_Feel free to suggest a new title for this issue btw ;)_

### Expected behavior

I think `this.scopedSchema` should reflect the actual "current" schema used for validation. Or there should be some secondary way to get at it.

### Steps to reproduce the issue

—

### Screenshots

—

### In which browser are you experiencing the issue?

not really applicable?

### Framework

- [X] Core
- [ ] React
- [X] Angular
- [ ] Vue 3
- [ ] Vue 2
- [X] Other (please specify in the Additional context field)

### RendererSet

- [ ] Material
- [ ] Vanilla
- [X] Other (please specify in the Additional context field)

### Additional context

I'm writing my own renderer set, taking inspiration/code from Angular material :D

**Comment by sdirix** [comment]
Hi @jessevdp, thanks for the report.

JSON Forms only partially supports "dynamic" features of JSON Schema when it comes to structure utilities. For example we support `oneOf/anyOf/allOf` in the React Material renderer set but we don't support [runtime specified keys](https://github.com/eclipsesource/jsonforms/issues/1765) nor [`if/then/else`](https://github.com/eclipsesource/jsonforms/issues/1518).

Validation use cases are supported via [Ajv](https://ajv.js.org/), which is why the validation works for you.

So there is no JSON Forms provided utility to access the relevant `allOf/0/then/properties/foo/properties/my-conditional` schema for your use case. It's also very hard to support this in practice, especially when also combined with `oneOf/anyOf/allOf`. The relevant subschema could be a whole array of contradicting schema specifications (`oneOf`).

Besides coding general support for this feature there are some workarounds you could do. For example you could extends the JSON Schema in a custom way to make the information locally available, e.g.

```json
{
    "type" : "object",
    "properties" : {
      "foo" : {
        "type" : "object",
        "properties" : {
          "my-condition" : {
            "type" : "boolean"
          },
          "my-conditional" : {
            "type" : "number",
            "custom": {
                "minimum" : 1.0,
                "maximum" : 10.0,
                "multipleOf" : 0.5,
                "path": "foo/my-condition",
                "is": true
            }
          }
        },
        "required" : [ ]
      }
    },
    "allOf" : [ {
      "if" : {
        "properties" : {
          "foo" : {
            "properties" : {
              "my-condition" : {
                "const" : true
              }
            }
          }        }
      },
      "then" : {
        "properties" : {
          "foo" : {
            "properties" : {
              "my-conditional" : {
                "minimum" : 1.0,
                "maximum" : 10.0,
                "multipleOf" : 0.5
              }
            },
            "required" : [ "my-conditional" ]
          }
        }
      }
    } ]
  }
```
Now you can easily check yourself whether the condition applies. You could also remove the whole `allOf/If/then/else` in case you don't need the proper JSON Schema validation.

A different way without changing the JSON Schema would be to modify the UI Schema.

```json
{
  "type": "VerticalLayout",
  "elements": [
    {
      "type": "Control",
      "scope": "#/properties/foo/properties/my-conditional",
      "options": {
        "slider": true,
         "minimum" : 1.0,
         "maximum" : 10.0,
         "multipleOf" : 0.5
      },
      "rule": {
        "effect": "SHOW",
        "condition": {
          "scope": "#/properties/foo/properties/my-condition",
          "schema": { "const": true}
        }
      }
    },
    {
      "type": "Control",
      "scope": "#/properties/foo/properties/my-conditional",
      "rule": {
        "effect": "HIDE",
        "condition": {
          "scope": "#/properties/foo/properties/my-condition",
          "schema": { "const": true}
        }
      }
    }
  ]
}
```
Here you can register a custom slider renderer for when `options: { "slider": true}` is set. The custom renderer then takes its values from the `options` object. JSON Forms will show your custom renderer when applicable. Here you can also remove the validation from the JSON Schema in case you don't need it elsewhere.

Both approaches have the downside that you need to touch your schema or UI Schema in some way to get them to work, however then you're able to declaratively configure your form. Of course if you don't need declaritive support you can always just encode all your logic in your custom renderer.

**Comment by jessevdp** [comment]
Thanks for the pointer. I ended up adding a custom `ifEnabled` object to the scoped schema of the property. It works perfectly.

```json
"my-prop" : {
  "type" : "number",
  "ifEnabled" : {
    "minimum" : 1.0,
    "maximum" : 10.0,
    "multipleOf" : 0.5
  }
}
```

We generate the schema's on the backend, so I was able to add some logic to generate these custom sections for properties that have those `if/then` JSON schema rules attached to them. 

I wrote the following helper to retrieve values from `this.scopedSchema` on the frontend:

```ts
import { JsonSchema } from '@jsonforms/core';

/**
 * Read an option from a scoped schema, checking both the root schema and the custom 'ifEnabled' section.
 * If the property is specified in both, the root value takes precedence.
 * 
 * @param schema 
 * @param property name of the property
 * @param defaultValue value to return if the property can not be found in any location
 */
export function getOptionFromSchema(schema: JsonSchema, property: string, defaultValue: any = null) {
    let rootValue = schema[property];
    let ifEnabledValue = schema['ifEnabled'] ? schema['ifEnabled'][property] : undefined;

    if (rootValue != undefined) return rootValue;
    else if (ifEnabledValue != undefined) return ifEnabledValue;
    else return defaultValue;
}
```

Usage:

```ts
this.min = getOptionFromSchema(this.scopedSchema, 'minimum');
this.max = getOptionFromSchema(this.scopedSchema, 'maximum');
this.multipleOf = getOptionFromSchema(this.scopedSchema, 'multipleOf', defaultStep);
```

**Comment by jessevdp** [comment]
Btw, sorry for opening a bug report. This was more of a question, but I couldn't find a place to just ask questions ;)
