### ISSUE TITLE
Regression of #1168: Empty string should be undefined

### ISSUE THREAD

**Issue by bennbollay** [eclipsesource/jsonforms#1810]
### Describe the bug

Changes made in #1168 were lost at some point, resulting in empty strings satisfying "required" validation checks.

### Expected behavior

Manually deleting the contents of a required field will generate a validation error.

Clearing a field via the [X] button will also generate a validation error.

### Steps to reproduce the issue

1. Download the seed app
2. Add "description" to the "required" clause in src/schema.json
3. Start the seed app
4. Clear the 'description' field by deleting all of the characters.
    * Note: no red error text generated.
    * Note: Data rendering on the left shows that the description has an "empty string" value.
5. Press the [X] button to force-clear the MaterialUI field.
    * Note: red error text is now generated.
    * Note: Data rendering on the left shows that no description parameter is present on the data object.

### In which browser are you experiencing the issue?

Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (arm64)

### Framework

React

### RendererSet

Material

### Additional context

This was reproduced on the 3.0.0 alpha-1 release as well as 2.5.1.

**Comment by sdirix** [comment]
Hi @bennbollay! Thanks for the report. However the reported issue is not really a regression but a design decision. The mentioned #1168 PR introduced the "empty field => undefined" behavior but it turned out to not be flexible enough. This is why we later introduced the additional "clear" button to distinguish between empty string and `undefined`.

If an empty string should not be allowed in your data set I would recommend adding a `"minLength": 1` attribute to your string property in JSON Schema. Then an empty string input will also show a validation error.

If you would like to overwrite the current behavior of JSON Forms you need to provide a custom renderer. That should be straightforward. You can simply reuse the existing renderer and just overwrite the `handleChange` method to also place `undefined` in the data when the handed over string is empty.

**Comment by bennbollay** [comment]
The `"minLength": 1` attribute, however, generates entirely the wrong type of error message - that the length is insufficient, not that the field is required.

In the <JsonForms handleChange>` property, changes to the passed in data do not impact the form validation.  Is there a handler we can hook on to do custom changes like this across the entire form that will generate errors in the validation phase?

**Comment by Ketec** [comment]
Came upon the same issue now with angular. And since the controls I'm using it for do not have any x/clear like material - required fields are always valid.
HAs there been any progress on making this configurable or a way to verride this behaviour?

**Comment by Ketec** [comment]
I have all custom renderers (started writing them, not using material) - however, looking at the angular adapter code I see it simply wraps the JsonFormsState.errors from core in validator and errors is empty when required + empty string.

**Comment by Ketec** [comment]
Problem is - setting the getEventValue result to null results in "must be a string".
Setting it to undefined shows required - but also now prefills the input with "undefined" as text.

**Comment by sdirix** [comment]
We changed the default to remove the string attribute when the input is empty with https://github.com/eclipsesource/jsonforms/pull/1984. The previous behavior of storing an empty string can be restored using a custom renderer.
