### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by StefanSchoof** [eclipsesource/jsonforms#1830]
### Is your feature request related to a problem? Please describe.

Angular 13 has been released (https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296)
jsonforms has currently a peer dependency to 12 https://github.com/eclipsesource/jsonforms/blob/7532a3e16558d9f0934bd5c602ccbe3a35ed9dab/packages/angular/package.json#L64 

### Describe the solution you'd like

Allow Angular 13 as peer dependency.

### Describe alternatives you've considered

Stay on angular 12 until jsonforms supports it

### Framework

Angular

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @StefanSchoof, thanks for the report! Usually Angular is backwards compatible enough so that our builds against older Angular versions still work with the latest one. Did you test JSON Forms against Angular 13? Is the peer dependency warning the only issue or is there something actually breaking?

**Comment by StefanSchoof** [comment]
I did an upgrade with `-force` and test a little bit and looks good. So I think there is a good chance that this is only the dependency version.

**Comment by StefanSchoof** [comment]
I think I found one other dependency issue. jsonforms is on zone.js 0.10
https://github.com/eclipsesource/jsonforms/blob/7532a3e16558d9f0934bd5c602ccbe3a35ed9dab/packages/angular-material/package.json#L70

and angular core is on 0.11
https://github.com/angular/angular/blob/f817e304053716d6a957c5c4863ea549ca9fbccd/packages/core/package.json#L20

**Comment by sdirix** [comment]
Good catch. Thanks for the input!

**Comment by p-stein** [comment]
Is the long term intention to try to pin jsonforms-angular to only a single recent version of Angular? The latest version of this project has seemingly dropped support for older versions of Angular and now targets 12 and 12 alone -- I'm curious what if any specific dependencies would exist that would necessitate picking only a single version of Angular, or if that change was unintentionally restrictive. Thanks!

**Comment by sdirix** [comment]
In general we always want to be compatible with the latest Angular version. If no changes are required in `@jsonforms/angular` and `@jsonforms/angular-material`, then we just extend our upper range and that's it. However whenever compatibility breaks because of some changes in Angular then we just update to the latest and restart this process.

If you'd want to stay on a previous version of Angular then you also need to stay on the latest JSON Forms version which supported that Angular version.

We did not test the current version with older Angular versions. If you want to take over the testing and report that it's actually backward compatible, then I'm happy to mark our releases as such.

**Comment by sdirix** [comment]
Hi @StefanSchoof, this is fixed with `3.0.0-beta.1`. Can you verify?

**Comment by StefanSchoof** [comment]
Yes, it is working. Finally only one other packing now is blocking from the angular 13 update.
