### ISSUE TITLE
scope or path

### ISSUE THREAD

**Issue by chenshuichao** [eclipsesource/jsonforms#1833]
### Is your feature request related to a problem? Please describe.

I think path is better than scope in ui schema

### Describe the solution you'd like

I think path is better than scope in ui schema

### Describe alternatives you've considered

I think path is better than scope in ui schema

**Comment by sdirix** [comment]
Hi @chenshuichao, thanks for the suggestion.

We use JSON Pointer based `scope`s because we need to resolve from the UI Schema to the corresponding (sub) JSON Schema. Can you discuss the advantages and disadvantages of using `scope` vs `path` and why you think that `path` is a better fit to the project?

Note that this would be a large change to at least JSON Forms Core and the bindings. Ideally you could demonstrate in a PoC how you would like to see this implemented and point out a migration path for existing users.

**Comment by sdirix** [comment]
Please reopen if you want to elaborate on the feature request
