### ISSUE TITLE
Infinite Loop when updating form data

### ISSUE THREAD

**Issue by PawanKolhe** [eclipsesource/jsonforms#1872]
### Describe the bug

When we try to save the form data object onChange via useState using object spreading, it causes an infinite rendering loop.

This works:
```
onChange={({ data }) => setFormData(data)}
```

This doesn't (infinite rendering loop):
```
onChange={({ data }) => setFormData({ ...data })}
```

**CodeSandbox:** https://codesandbox.io/s/dynamic-forms-json-forms-infinite-4wwhp?file=/src/App.tsx

### Expected behavior

Setting a new object as data should not cause infinite rerendering.

### Steps to reproduce the issue

1. In this codesandbox (https://codesandbox.io/s/dynamic-forms-json-forms-infinite-4wwhp?file=/src/App.tsx), uncomment line 84 and comment out line 82.
2. It will cause the issue

### In which browser are you experiencing the issue?

Google Chrome - Version 97.0.4692.71 (Official Build) (64-bit)

### Framework

React

### RendererSet

Material

### Additional context

My reason for doing this is so that I can update a field based on the value of another field. I'm wanting to modify the data object before it is updated.

**Comment by sdirix** [comment]
Hi @PawanKolhe,

this is expected behavior. Whenever you hand over a new object to JSON Forms it will validate and render it. This is typical React behavior, and is also what happens in other libraries like `react-table`. Therefore when a new object is handed over with each render pass you will end up in an endless loop.

To solve this you should only hand over a new object when it has some modified data. So instead of spreading the object (i.e. creating a new object) unconditionally, you should only do it when you actually modify something within it.

**Comment by sdirix** [comment]
I created a ticket for the documentation to better explain this behavior: https://github.com/eclipsesource/jsonforms2-website/issues/214
