### ISSUE TITLE
uischema input for angular is of type UISchemaElement which is not the actual uischema

### ISSUE THREAD

**Issue by Ketec** [eclipsesource/jsonforms#1883]
### Describe the bug

uischema: UISchemaElement;

```
export interface UISchemaElement {
  type: string;
  rule?: Rule;
  options?: { [key: string]: any };
}
```
While schema data could be 
```
{
  "type": "HorizontalLayout",
  "elements": [
    {
      "type": "Control",
      "label": "Name",
      "scope": "#/properties/name"
    },
    {
      "type": "Control",
      "label": "Birth Date",
      "scope": "#/properties/birthDate",
      "options": {}
    }
  ]
}
```

### Expected behavior

Has correct type/interface.

### Steps to reproduce the issue

This seem to be a side-effect of JsonFormsOutlet extending base that passes UISchemaElement as type

### In which browser are you experiencing the issue?

All

**Comment by sdirix** [comment]
Hi @Ketec, thanks for your interest in JSON Forms. Our typings could be improved so that they can be easier used, however it's possible to use them without casting. You need to specifically declare what type of `UISchemaElement` you're using, e.g. `ControlElement`. Then TS will recognize that your prop is actually valid. See [here](https://github.com/eclipsesource/jsonforms/issues/1818) for more information.
