### ISSUE TITLE
lit-element/WebComponent Implementation

### ISSUE THREAD

**Issue by hegsie** [eclipsesource/jsonforms#1906]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Rather than using the React/Vue/Angular frameworks, it would be nice to be able to use a raw web component or lit-element implementation

### Describe alternatives you've considered

There are some WebComponents that are more basic than this but none at this level of Schema/JSON dev

### Framework

Other (please specify in the Additional context field)

### RendererSet

Material

### Additional context

Lit-Element/WebComponent

**Comment by GitpayPop** [comment]
This issue was added to Gitpay, check the task [https://gitpay.me/#/task/614](https://gitpay.me/#/task/614) 💝

[About Gitpay platform](https://gitpay.me).

For portuguese, you can [access the portuguese version](https://github.com/worknenjoy/gitpay-github-app/blob/master/first-comment.pt-br.md)

### 📋 Step by Step

#### If you are the task owner who created this issue
- [x] 🔔 ***Issue open*** an issue was created
- [x] 👌 **Issue added on Gitpay** this issue was added on gitpay [https://gitpay.me/#/task/614](https://gitpay.me/#/task/614)
- [ ] 📝 **Add bounties** A bounty is added to get things done
- [ ] 📝 **Set a deadline** A deadline to finish the task (optional)
- [ ] 💾 **Choose a contributor interested** You can choose someone interested that will be able to solve your issue

#### If you want to contribute and be rewarded
- [ ] 💾 **A contributor is interested** You can show interest on the task page clicking in "I'm interested"
- [ ] 💾 **You can offer** You can make an offer
- [ ] 🔀 **You can be assigned**. You can be assigned, you should work on the task and send a Pull Request.
- [ ] 💬 **Review** Ask in comments for a review :)
- [ ] 🏁 **Approved** Once approved you will receive your payment

### 📋 Task status
- [x] ***OPEN***
- [ ] ***IN PROGRESS***
- [ ] ***DONE***

### Good to know

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. For a more compreenhensive guide to create the Pull Request properly, you can access: https://guides.github.com/activities/hello-world/

3. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

### 🤔❓ Questions
Leave a comment below!
This issue was a comment made by our GitpayBot [Gitpay Bot](https://github.com/gitpaybot).

**Comment by sdirix** [comment]
Hi @hegsie,

At the moment we have no plans to create and maintain WebComponent bindings and/or a WebComponent-based renderer set ourselves. If you are interested in such an offering you might want to consider our [professional support](https://jsonforms.io/support) by which we would help you to create WebComponent bindings and renderer set, ranging from answering questions to taking over the full implementation.

Note that in the past [we offered a WebComponent based JSON Forms by wrapping the React bindings](https://github.com/eclipsesource/jsonforms/tree/60ffbd9e65a513b15086bcf053eba6640ef8e4a7/packages/webcomponent). You could replicate a similar approach if you need WebComponent support. Also you could take a look at [this WebComponent wrapping of an Angular Material based JSON Forms](https://github.com/eclipsesource/jsonforms-angular-webcomponent).

**Comment by hegsie** [comment]
hmm I don't really want to use any of the options you currently provide, I don't want to pull in react, angular or vue when I don't currently use/need, how much work would estimate it to be to implement a raw JS render set, the web component bindings are provided for free by the browser?
