### ISSUE TITLE
Dynamic update oneOf dependent to List

### ISSUE THREAD

**Issue by tujger** [eclipsesource/jsonforms#1938]
### Is your feature request related to a problem? Please describe.

Probably, it is already possible to solve this but I have no idea. 
Say, we have the list:

```
{
  properties: {
    list: {
      type: "array",
      items: {
        type: "object",
        properties: {
           id: {
             type: "string"
           },
           name: {
              type: "string"
           }
        }
      }
    }
  }
}
```

How to define another property dependent to this one? I.e.:

```
{
  properties: {
    list: {
      type: "array",
      items: {
        type: "object",
        properties: {
           id: {
             type: "string"
           },
           name: {
              type: "string"
           }
        }
      }
    },
    value: {
      type: "string",
      oneOf: {
         const: "#/properties/list/properties/id",
         title: "#/properties/list/properties/name"
      }
    }
  }
}
```

Expecting to dynamically update `oneOf` for `value` when the items added or removed from `list`.

### Describe the solution you'd like

Now I implement it with custom control with overriding handleChange and specific dispatch for updated property.

### Describe alternatives you've considered

Nothing

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @tujger, please use our [discussion board](https://jsonforms.discourse.group/) for questions instead of creating new issues.

JSON Schema only has very limited capabilities to refer to instance values (i.e. you can only check for hard coded values). Therefore we also don't have builtin support for that.

Using a custom control for your use cases makes a lot of sense here.
