### ISSUE TITLE
Documentation for i18n support

### ISSUE THREAD

**Issue by collegewap** [eclipsesource/jsonforms#1963]
### Describe the bug

I could see that i18n was implemented through https://github.com/eclipsesource/jsonforms/pull/1825, however, there is no documentation/example on how to use it.

### Expected behavior

A simple example would be helpful.

### Steps to reproduce the issue

NA

### In which browser are you experiencing the issue?

Chrome

**Comment by sdirix** [comment]
Hi @collegewap, the issue is tracked [here](https://github.com/eclipsesource/jsonforms2-website/issues/207) and [here](https://deploy-preview-222--jsonforms.netlify.app/) you can find a first version of the upcoming documentation. Let me know whether something is missing for by commenting in the [PR](https://github.com/eclipsesource/jsonforms2-website/pull/222).
