### ISSUE TITLE
Provide vanilla ViewerRenderers for the schemas

### ISSUE THREAD

**Issue by kimamil** [eclipsesource/jsonforms#1995]
### Is your feature request related to a problem? Please describe.

jsonforms provides a neat way to quickly design reactive forms. When developing applications, I usually use the same schema to not only render a form, but also to display the data to the user.

I see jsonforms as a rendering engine for data that would be fit for my purposes. I could of course go ahead and define a new set of custom renderers to do that. However, I can imagine that there's input-specific features (e.g. validation) that could be skipped for displaying the data.

### Describe the solution you'd like

I'd like a basic set of vue-vanilla renderers that allow me to simply display the data from the same schema that I used for creating my jsonforms, without the input-related features.

### Describe alternatives you've considered

- writing my own vue components (there are some challenges with that and I guess I do understand now why there's a dispatch-renderer in the jsonforms library :D )
- writing custom jsonforms renderers

### Framework

Vue 3

### RendererSet

Vanilla

### Additional context

I used jsonforms for the first time and I love it - had I only discovered it 5 projects earlier :D

**Comment by sdirix** [comment]
Hi!

I'll close this issue as we don't plan to provide such a view-only renderer set. However the good news is that it's really easy to create one:

 - the simple layout renderers (`VerticalLayout`, `HorizontalLayout`, `Group`) can just be reused as is
 - only one primitive control renderer is needed. It can match on all primitive types like `number`, `string` etc. and then just render the values as text instead of binding them against an input. Of course you still might want to specialize a bit, e.g. showing booleans as disabled check boxes
 - Maybe a different renderer for arrays. Again it can be very simple

Besides that note that there are two useful props for the root `json-forms` component:

 - `readonly` which renders all inputs disabled. Maybe this is even enough for your use cases and you don't even need a special renderer set then?
 - `validationMode: 'NoValidation'` which disables validation as it's not needed anyway
