### ISSUE TITLE
Add color picker field

### ISSUE THREAD

**Issue by sinedie** [eclipsesource/jsonforms#2032]
### Is your feature request related to a problem? Please describe.

Sometimes you need to store colors in a json configuration file.

### Describe the solution you'd like

It would be nice to select colors in a easy way and dont have to write the rgb or hex value by hand.

### Describe alternatives you've considered

Maybe I can create a custom renderer but just landed into this library. (awesome work)

### Framework

Core, React

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @sinedie,

We don't plan to support a color picker out of the box because:

- This is not a foreseen use case of JSON Schema so we would need to define an arbitrary way of storing colors which will most likely not fit to most use case
- A color picker UI is often very customized to the use cases it's used in so a default implementation still might not be that useful

However I think a color picker would make for a great tutorial or custom renderer demo. So I would recommend posting in our [community](https://jsonforms.discourse.group/) asking for an implementation or posting one yourself.

**Comment by afcirillo96** [comment]
Did someone made a color picker already?

**Comment by lucas-koehler** [comment]
Hi @afcirillo96 , there is not color picker in JSON Forms and we still do not plan to add one to the repository for the reasons outlined in https://github.com/eclipsesource/jsonforms/issues/2032#issuecomment-1307803067 .

Here, your question is likely not seen by other community members. Thus, I suggest you ask in the [community forum](https://jsonforms.discourse.group/) instead. Maybe other members of the community can share ideas or an implementation.
