### ISSUE TITLE
Are you actually maintaining this repo??

### ISSUE THREAD

**Issue by lcervo** [eclipsesource/jsonforms#2049]
### Describe the bug

The angular code is all over the place. It doesn't compile, it has A LOT of lint and logic errors. It's like it has been written by a bunch of junior devs with no clues what they are doing. 

Do you have plans to make it work and support it?

### Expected behavior

the angular project (including the material one) should at least compile.

### Steps to reproduce the issue

just open the repo with your IDE of choice and compile the angular project(s)

### In which browser are you experiencing the issue?

it doesn't matter

### Which Version of JSON Forms are you using?

xxx

### Framework

Angular

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @lcervo,

> Are you actually maintaining this repo??

The answer is: Yes

Thanks for the feedback. As this is an open source project, feel free to contribute improvements where you feel the project is lacking. If you want to make sure your contributions can be merged, I would like to recommend open concrete issues describing the problem and suggestions on how to fix them. If these fit into the ongoing development of the framework we'll happily review your contributions and merge if they meet our quality standards.

It seems that you are struggling setting up the development environment on your machine. Please make sure that you followed our short [development guide](https://github.com/eclipsesource/jsonforms/tree/91f351daa7b7ae4bb0f0dffd47f00bb6cf682ec1#developers-documentation) in the root Readme, especially the [First time setup](https://github.com/eclipsesource/jsonforms/tree/91f351daa7b7ae4bb0f0dffd47f00bb6cf682ec1#first-time-setup) and the [build/testing scripts](https://github.com/eclipsesource/jsonforms/tree/91f351daa7b7ae4bb0f0dffd47f00bb6cf682ec1#build--testing). If there are issues related to your environment you might want to try the [VS Code dev container setup](https://github.com/eclipsesource/jsonforms/tree/91f351daa7b7ae4bb0f0dffd47f00bb6cf682ec1#vs-code-dev-container) instead. You can also check the typical flow of a build in our automated builds which run on every PR and merge to master. [These run successfully](https://github.com/eclipsesource/jsonforms/actions/runs/3426711535/jobs/5708836723#step:4:157).

As the main question of this issue is answered I'll close it for now. Feel free to comment if you disagree.
