### ISSUE TITLE
When element becomes invisible, its data should also be removed

### ISSUE THREAD

**Issue by CarlosNZ** [eclipsesource/jsonforms#2118]
### Is your feature request related to a problem? Please describe.

If you have an element whose visibility is dependent on another, it can happen that a user will have already entered a value, then changed something else making the item invisible. But the data they entered is still in the data object, which can lead to inconsistent or erroneous form data being saved.

I would think that when an item is invisible, then its data should be purged.

### Describe the solution you'd like

On data change, invisible UI elements should have the corresponding data removed.

### Describe alternatives you've considered

Perhaps this could be an optional behaviour?

### Framework

Core

### RendererSet

Material

### Additional context

Perhaps there is a rationale for it being the way it is? Perhaps it's too complex to implement, or you'd rather leave it to developers to manage this kind of thing themselves?

If you agree that the suggested behaviour would be desirable, it'd be good to know as I'd be keen to spend some time suggesting an implementation and making a PR to implement this in JSON Forms. Otherwise I'll devote the time to coming up with a solution in my own project's implementation.

Thanks.

**Comment by sdirix** [comment]
Hi @CarlosNZ,

Thanks for the suggestion. This behavior is on purpose for multiple reasons:
 - We want to avoid modifying data just by rendering it
 - Hiding data is from our point of view a UI operation and not a data manipulation operation
 - Services consuming the data must be able to handle the superfluous data anyway

A common UX issue when deleting data when controls become invisible is:
 1. The user enters data
 2. The user does some interaction which hides the previous entered data (e.g. click some boolean)
 3. They revert this interaction
 4. The data is now gone and the user has to add it again. The user becomes frustrated

The cleaner way in most use cases is to remove the unwanted data in a processing step outside the form, i.e. handling it outside of JSON Forms. Then you can decide between: Doing this processing step only on "submit" so that the UX issue described above can not occur, or doing this processing step on every change incoming from JSON Forms so the data is actually also removed from the form.

Does this make sense for you?

**Comment by CarlosNZ** [comment]
Thanks @sdirix -- yes that makes sense.

It's actually kind of a tricky problem to deal with, as validating data based on the a UI state is not really something we want to be doing -- and yet, it does kind of make sense in some situations. But yes, I can see that handling it outside JSON Forms would be the way to go.

I think perhaps some kind of "tidy-up" on Submission of the form is probably the best approach. Will have a bit more of a think as to how we can implement this in our project.

**Comment by sdirix** [comment]
Sounds good to me. I'll close this ticket for now. Feel free to comment and/or re-open if you think further discussion is needed.
