### ISSUE TITLE
Ability to display "Template literals"

### ISSUE THREAD

**Issue by DylanBarber** [eclipsesource/jsonforms#2150]
### Is your feature request related to a problem? Please describe.

Unable to display a dynamic sentence with variables in the middle (See below)

### Describe the solution you'd like

I am attempting to display text such as:

"Thank you, Alphabet Inc, for your business!"

I would like to see a sort of label that takes in text such as "Thank you, {{businessName}}, for your business!" and injects in the variable name like a template literal does.

Maybe there is a control that does so already but I have looked everywhere and can't seem to find it!

### Describe alternatives you've considered

I've tried making my own custom renderer that takes a `templateVars` object into the options and then string replaces the displayText (Also passed into options) to then render it like so:

"options": {
    "templateVars": {
          "businessName": "#/properties/business/name"
     }
     displayText: "Thank you, {{businessName}}, for your business!"
}

However, what ends up getting displayed is the following:
"Thank you, #/properties/business/name, for your business!"
as I'm assuming JSONForms doesn't resolve the businessName. 
I'm probably doing something wrong with my custom renderer but the community discussion around custom renderers isn't broad enough for me to find concise "how-to" type information on making this.

### Framework

Core

### RendererSet

Vanilla

**Comment by sdirix** [comment]
Hi @DylanBarber,

There is no built-in solution for this and currently we also do not plan to support this out of the box. This is the ideal use case for a custom renderer which can then offer all options you need.

However the custom renderer has to perform all the (custom) logic itself. For example JSON Forms will not eagerly look at the UI Schema and resolve all the JSON Pointers it can find. This is why the `businessName` in your example is still just the JSON Pointer.

The good news is that you can of course reuse the utilities of JSON Forms to resolve your pointer. In your custom renderer you have access to the form wide `data`. To resolve the JSON Pointer you can do something like this:

```
const businessNameDataPath = toDataPathSegments(uischema.options.templateVars.businessName).join('.');
const businessName = Resolve.data(data, businessNameDataPath)
```

If you already specify the actual instance path to the data in your UI Schema instead of a JSON Pointer to the sub JSON Schema then you can skip the first line.

Using that you can then render your template string. Of course the logic can be generified so that you are then able to have a generic `TemplateRenderer`.

---

Note that we also have a [community forum](https://jsonforms.discourse.group/). For questions please create a post there first instead of creating an issue.
