### ISSUE TITLE
ERROR DOMException in browser console

### ISSUE THREAD

**Issue by dimpon** [eclipsesource/jsonforms#2166]
### Describe the bug

Angular 15 + jsonforms 3.1.0
When a page with form is opened error appears in chrome console.
Reproduced only if `showUnfocusedDescription: true`  and for fields with `type: number | integer.`

In Chrome, Edge: ERROR DOMException: Failed to execute 'setAttribute' on 'Element': '||' is not a valid attribute name.
In Firefox: ERROR DOMException: String contains an invalid character

Pet app for reproducing.
https://github.com/dimpon/angular-with-jsonforms

### Expected behavior

No errors in the console

### Steps to reproduce the issue

1. Build and run pet app https://github.com/dimpon/angular-with-jsonforms
2. Open in browser
3. See error in the console

### In which browser are you experiencing the issue?

Chrome Version 114.0.5735.199 (Official Build) (64-bit)

### Which Version of JSON Forms are you using?

v3.1.0

### Framework

Angular

### RendererSet

Material

**Comment by lucas-koehler** [comment]
Hi @dimpon ,

thanks for the report :heart: . I could reproduce this also with  Angular 12. This was in fact caused by an incorrect placement of a `"` in the number renderer. I opened a PR for this.
Note that we don't support Angular 15, yet. So you might run into other issues that are not bugs. See https://github.com/eclipsesource/jsonforms/issues/2085.
