### ISSUE TITLE
Property with reference is not rendered

### ISSUE THREAD

**Issue by KIC** [eclipsesource/jsonforms#2187]
### Describe the bug

While the address renders fine, given the json schema below, the parent does not render at all.
```
type: "object",
definitions: {
  Client: {
      "address": {
          "type": "array",
          "items": {
              "$ref": "#/definitions/Address"
          }
      },
      "parent": {
          // https://jsonforms.io/docs/tutorial/multiple-forms#interlinked-inputs
          "$ref": "#/definitions/SearchableObject/properties/a_very_special_field"
          //"$ref": "#/definitions/SearchableObject"
          //"type": "object"
          //items: {"$ref": "#/definitions/SearchableObject"}
          //item: {"$ref": "#/definitions/SearchableObject"}
      }
  },
  SearchableObject: {
      "type": "object",
      "properties": {
          "a_very_special_field": {
              "type": "integer"
          }
      },
      "required": []
  },
 properties: {
    "Client": {
        "$ref": "#/definitions/Client"
    }
}
```

As soon as I turn the `parent` into an array field just like the `address` it renders fine again (but of course is an array which is not what I need).

### Expected behavior

Render the Sub-Form for the `parent` object like for array fields

### Steps to reproduce the issue

Render form using the jsonschema above und leave the uischema undiefined.

### In which browser are you experiencing the issue?

Google Chrome 

### Which Version of JSON Forms are you using?

3.1.0

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @KIC,

The posted schema is invalid and/or incomplete. For example the `Client` is not a valid JSON Schema. `address` also seems to point to a non-existing `Address`.

I adjusted it to the following

```
{
  "type": "object",
  "definitions": {
    "Client": {
      "type": "object",
      "properties": {
        "address": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Address"
          }
        },
        "parent": {
          "$ref": "#/definitions/SearchableObject/properties/a_very_special_field"
        }
      }
    },
    "Address": {
      "type": "string"
    },
    "SearchableObject": {
      "type": "object",
      "properties": {
        "a_very_special_field": {
          "type": "integer"
        }
      },
      "required": []
    }
  },
  "properties": {
    "Client": {
      "$ref": "#/definitions/Client"
    }
  }
}
```

Then I was able to reproduce the problem: The "parent" is not rendered. The error seems to be the same as reported [here](https://jsonforms.discourse.group/t/nested-ref-not-showing-no-ui-schema/1763). As noted in the link, the problem is that the [MaterialObjectRenderer does not hand over enough context to the UI Schema generator](https://github.com/eclipsesource/jsonforms/blob/9146b0fdf5913d2251fadd5435d2c7e813db6f71/packages/material-renderers/src/complex/MaterialObjectRenderer.tsx#L59-L60) to successfully resolve the reference to the `a_very_special_field`.

This needs to be fixed. Contributions welcome!
