### ISSUE TITLE
EnumNames is not supported

### ISSUE THREAD

**Issue by NumanAnees** [eclipsesource/jsonforms#2211]
### Problem 
I want to give my enum values a title/name but am unable to do so. 

```
      enum: ['None', 'Start', 'Stop', 'Pause', 'Resume'],
      enumNames: ['NoneAction', 'StartAction', 'StopAction', 'PauseAction', 'ResumeAction'],
```

### Describe the solution you'd like

I want to show user NoneAction,StartAction instead of just None and Start.

### Describe alternatives you've considered

This EnumNames feature is supported by rjsf but not supported in the leatest version of jsonforms.

### Framework

React

### RendererSet

Material

### Stackblitz link

https://stackblitz.com/edit/vitejs-vite-npqcxt?file=src%2FApp.jsx

**Comment by sdirix** [comment]
Hi @NumanAnees,

`enumNames` is not part of the official JSON Schema spec which is why it's not supported out of the box in JSON Forms.

Out of the box we support enum labels via [`oneOf` constructs](https://jsonforms.io/docs/multiple-choice) or via the [`i18n` support](https://jsonforms.io/docs/i18n).

It's also very straightforward to support this via custom renderers. You can reuse the [enum renderer](https://github.com/eclipsesource/jsonforms/blob/77624c6ab6c0f3db98abe3175547bbd51f7510bb/packages/material-renderers/src/controls/MaterialEnumControl.tsx) and simply override the determined `options` labels via the `enumLabels` of the schema.

**Comment by sdirix** [comment]
Closing this issue for now as we don't plan to implement this.
