### ISSUE TITLE
Vue-Vanilla OneOfRenderer throws warning "Missing required prop: "rootSchema" "

### ISSUE THREAD

**Issue by davewwww** [eclipsesource/jsonforms#2265]
### Describe the bug

In a schema with a oneOf construct, the OneOfRenderer throws this error: **Missing required prop: "rootSchema"** 

```json
{
    "type": "object",
    "properties": {
      "quantity": {
        "oneOf": [{ "type": "string" }, { "type": "number" }]
      }
  }
}
```

to reproduce: https://codesandbox.io/p/devbox/jsonforms-oneof-error-mng4g8

### Expected behavior

No warning should be thrown.

### Steps to reproduce the issue

1. Go to (https://codesandbox.io/p/devbox/jsonforms-oneof-error-mng4g8)
2. Click on "Show form"
4. See error at Dev console

### Which Version of JSON Forms are you using?

v3.2.1

### Framework

Vue

### RendererSet

Vanilla

**Comment by sdirix** [comment]
Good find!

The `rootSchema` is required in case one of the `oneOf` points outside of the current sub-schema. As we do not hand it over, some nested one ofs will not work.

The problem seems to be [here](https://github.com/eclipsesource/jsonforms/blob/9d3f706d4dfebcc7409e075a0622d1f50c2e1f3d/packages/vue-vanilla/src/complex/OneOfRenderer.vue#L3-L7), as we don't pass the root schema.

Would you be interested in contributing a fix?

**Comment by davewwww** [comment]
I will have a look at it and try to fix it.
