### ISSUE TITLE
Only one Json

### ISSUE THREAD

**Issue by anhaabaete** [eclipsesource/jsonforms#2331]
### Is your feature request related to a problem? Please describe.

In a context of system distribuited and services, is hard control "UI" form the backend.

### Describe the solution you'd like

Work only one JSON with minimal to work, with ui

### Describe alternatives you've considered

join the 2 json in only one

### Framework

Core

**Comment by lucas-koehler** [comment]
Hello @anhaabaete , thanks for raising this issue.
However, this is not a change we will make: The Json Schema and UI Schema are deliberately split because they address two separate concerns: The first defines the data structure while the second defines the UI.

I do not see how having two JSON objects - one each for the schema and the ui schema - poses a problem in distributed systems. For instance, you could send both of them encapsulated in one parent object.

Regarding your concern about it being hard to control the UI from the backend: This problem is solved by the separation into JSON Schema and UI Schema: You define your data structure once in the JSON Schema and can then send a UI Schema to define the UI.
