### ISSUE TITLE
interface UISchemaElement type  error

### ISSUE THREAD

**Issue by see7788** [eclipsesource/jsonforms#2332]
### Describe the bug

interface UISchemaElement param key is “options”:https://jsonforms.io/api/core/interfaces/uischemaelement.html
demo param key is "elements" :https://jsonforms.io/docs/uischema/layouts

### Expected behavior

type error

### Steps to reproduce the issue

type error

### Screenshots

type error

### Which Version of JSON Forms are you using?

3.2.1

### Framework

React

### RendererSet

Material

### Additional context

type error

**Comment by see7788** [comment]
How can I use uischema in @jsonforms/react without encountering the error that elements does not exist?

**Comment by MartinDavi** [comment]
Yeah this is confusing - why does the JsonForms component's `uischema` prop expect only a `UISchemaElement` according to its type, but accepts a `Layout` in practice?

Are the types not complete?

**Comment by sdirix** [comment]
`Layout` is a descended of `UISchemaElement`. So if you actually hand a `Layout` in, it will work. It's only if you hand in an object which is a valid `Layout` but not typed as such where this problem occurs. As noted [here](https://github.com/eclipsesource/jsonforms/issues/2109), we agree that it makes sense to adjust the types so that they are more friendly to use.
