### ISSUE TITLE
Integrate resolution mechanism for remote json objects

### ISSUE THREAD

**Issue by planger** [eclipsesource/jsonforms#3]
With the integration of `dojox.json.ref` we now have support for referencing json objects (`$ref:`) by path and by id. This resolves also cross-reference scenarios and cyclic references among objects. See also the tests of `app/components/version/jsonref_test.js`.

Now we need to investigate how to best support referencing json objects that have not been fetched from a remote API yet. This involves providing and integrating different resolution strategies (such as, when to resolve which remote objects) to provide the necessary control on when how much data should be retrieved during resolution.

**Comment by edgarmueller** [comment]
After some consideration I decided to close this issue, because of the following reasons:

- It is the responsbility of the backend to handle references between domain objects. I would think that in most cases IDs should be sufficient to represent references, like it is the case with most backend I know of
- You would still need to configure displaying of references, e.g. if a reference is clicked where does it take you? I would guess that you'd still need to adjust the routing accordingly
- We are trying to keep dependencies minimal

Overall, I think the benefit of such a resolution mechanism is quite small and most use cases can be handled by using the `ReferenceControl`.

Please, re-open if you don't agree.
