### ISSUE TITLE
Support entering a date only

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#453]
Currently we only support a control for a string with the date-time formatting. In consequence a control for birth date is pretty strange since one need to enter a time as well otherwise the input is not valid.

**Comment by eneufeld** [comment]
@koegel where are you seeing this?
actually this is the other way round. we only support date but nothing else ...

**Comment by koegel** [comment]
http://github.eclipsesource.com/jsonforms/#/examples/layouts

**Comment by koegel** [comment]
Maybe specific to the material renderer?

**Comment by eneufeld** [comment]
no, you are reading the error incorrectly. 
it tells you, that the entered data is not conform to the date-time format, the shown renderer is also a string renderer.
If you look at the live example, you can see, that if you change the type to date of the birthdate that you will get a calendar widget. 
We need to update the examples to use date instead of date-time.

**Comment by koegel** [comment]
OK, I see, but this is not standard compliant then:
http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3.1
In the standard there is no date format

**Comment by koegel** [comment]
But fine for me anyway

**Comment by koegel** [comment]
Resolution is then to change the schema in the examples

**Comment by eneufeld** [comment]
should be done with #482
