### ISSUE TITLE
i18n Support

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#496]
JSON Forms must support i18n for labels of properties (shown in controls) and labels in categories and groups. Furthermore we need to examine all UI schema elements if they contain strings that are to be shown in the form and also support i18n for them. 
i18n must be aligned with EMF Forms support to enable a smooth integration.

**Comment by eneufeld** [comment]
Also for validation messages

**Comment by edgarmueller** [comment]
For translating string based on the schema/UI schema we should have a look at [react-redux-i18n](https://github.com/artisavotins/react-redux-i18n).

For dates and numbers, look at the [Intl doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl).

**Comment by edgarmueller** [comment]
I had a look at the current state of the i18n support and I would suggest to do the following:
- for the time being, drop support for number formatting as it takes too much effort to implement
- remove `transformProps` reducer (since functions should not be part of the state) and replace i18n with custom middleware, which would intercept the `INIT` action and transform the `uischema` for translating any labels and descriptions

This approach is cleaner and redux-idiomatic.

**Comment by edgarmueller** [comment]
Yes, I think we can close it for now.

**Comment by ksze** [comment]
How does i18n work? Where is it documented?

**Comment by sdirix** [comment]
> How does i18n work? Where is it documented?

Hi @ksze. This issue is quite old, see [this issue](https://github.com/eclipsesource/jsonforms/issues/1751) for a short description of the current mechanism and how we intend to change it.
