### ISSUE TITLE
Enum properties are rendered as regular input instead of select element

### ISSUE THREAD

**Issue by muenchdo** [eclipsesource/jsonforms#64]
Hi, in the latest version, enum properties are not rendered as select elements, but as regular inputs instead. It still works in the live demo, however the code there seems outdated.

This is probably because in JSONSchema the type of an enum is (I think) always `string`, but never `enum`. However in the control template's `ng-switch-when`, the select input is only rendered when the `schemaType` equals `enum`.

I have prepared a pull request which should fix the problem. I will submit it later.

**Comment by sdirix** [comment]
Thanks for your efforts! You are right, currently some of the inputs are broken. I will look into your changes as soon as I can (probably tomorrow).

Welcome to JSONForms ;)

**Comment by sdirix** [comment]
As you may have noticed the renderer was rewritten before we could merge your contribution, so this bug is already fixed ;) 

We still would like to integrate your unit test since one can never have enough tests. The more the better!

But before we can merge your unit test you need to sign our <a href="https://github.com/eclipsesource/jsonforms/blob/master/CLA.md">CLA</a>. More information can be found in our (new) <a href="https://github.com/eclipsesource/jsonforms/blob/master/CONTRIBUTING.md">CONTRIBUTING.md</a>.

Thank you for your work and sorry for the delay. Future contributions will be processed much faster. See you soon ;)

**Comment by sdirix** [comment]
Your unit test was merged in #97.

Thanks for your contribution!
