### ISSUE TITLE
Stay on same repo with JSON Forms 2

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#648]
Options: 
1. Both on same repo
2. 2 on new repo
3. 1 on new repo

**Comment by koegel** [comment]
@edgarmueller: Whatś your angle on this?

**Comment by koegel** [comment]
Main argument from my pov is to keep history, community and traffic for JSON Forms 2 and therefore go for option 1 or 3.

**Comment by edgarmueller** [comment]
I'd be for option 2.

* Issue handling is easier as it's clear from the context for which major version the issue is relevant. 
* JSONForms 2 is really a re-write and has not much in common with the 1st version except the concepts, so I don't think the history argument is a valid one.
* It'd be unnecessarily confusing for existing users if we change our repo layout from one day to another

To keep visibility and traffic we could link the JSON Forms 2 repo from the current one in the README right in the heading once we certain that JSONForms 2 is production

**Comment by koegel** [comment]
- We could use a tag to distinguish the tickets, anyway how many tickets do we actually get from external users really?
- The schema and UI schema remain the same also  :)   
- a link does not preserve the development history from an activity point of view and also looses the stars. 

Given your arguments, why not go for option 3?

**Comment by edgarmueller** [comment]
Rename current master to jsonforms1 and react to master

**Comment by edgarmueller** [comment]
The `react` branch has been published as `master`, former `master` has been renamed to `jsonforms-1`. We can still move the branch to a different repo if necessary.
