### ISSUE TITLE
Dependant fields using rules?

### ISSUE THREAD

**Issue by gentledepp** [eclipsesource/jsonforms#661]
Hi!

I have a simple scenario and don't quite know how this can be done with jsonforms:

I have two dropdowns, where the second dropdown is dependant on the first one.
For the sake of simplicity, the first one is  "country", and the second one "state".
Now when someone selects a country (e.g. "USA") I would need
1) the "state" dropdown to be made editable (was readonly before)
2) populate the "state" dropdown with all states of the united states only.

Of course, once the "country" dropdown is set to another country, the dependant "state" field must be cleared!

How can I accomplish something like that - especially if the list of states must come from some rest api.

**Comment by gentledepp** [comment]
As far as I can see from the [JSON Schema address example](http://json-schema.org/example/address.json), this should (somehow) be achievable using "dependencies", right?
Is that supported?

**Comment by koegel** [comment]
Using JSONForms 1 (the current master) this is not possible, as rules only support to hide elements.
If you use JSONForms 2 (will be released in January) this is possible, by adding a rule to disable the state control if the country value is undefined. For the state field you will need a custom renderer because of two reasons:
1. because you want to get data from a rest service
2. because you want to clear the value if the country value changes
Implementing a custom renderer is quite simple, see http://jsonforms.io/#/docs/customrenderer-ts

**Comment by gentledepp** [comment]
Thank you for your response!
What is the intention behind creating a "JSONForms 2" - are you porting it to Angular 2/4 ?

**Comment by koegel** [comment]
Yes, we wanted to add compatibility with Angular 2/4 and also with other frameworks such as React. Therefore we have build JSON Forms 2 on web components.

**Comment by edgarmueller** [comment]
We have published a 1st release candidate of JSON Forms 2 (based on React/Redux) last week. 
I think this use case should be covered by setting the [DISABLE](http://jsonforms.io/api/core/enums/ruleeffect.html#disable) rule effect. For an example of a basic rule, see [this example](http://jsonforms.io/examples/rule). If you have any questions or encounter issues, feel free to re-open.
