### ISSUE TITLE
Inferno migration issues

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#671]
Open issues:
- [x] DnD support missing
- [x] Remove remaining global state, e.g. Styling registry or JsonForms global object, should to be removed
- [x] Schema service must be ported (does not work with redux due to mutable operations)
- [x] Tree/Categories styling for Material does not exist (hence appears broken)
- [x] Raise test coverage once again
- [x] Check for React compatibility

**Comment by eneufeld** [comment]
- split renderer and style switcher, eg when using materialize?
- [example/dynamic2.ts](https://github.com/eclipsesource/jsonforms/pull/670/files#diff-094f67d0c6429ec50ab91c730d26c97a) reactivate/fix commented out code
- templates/person.ts why duplicate age and height?
- why split RatingControl and Rating?
- example_plain/index.html -> reactive dark.css and labelfixed.css, remove inline style?
- why do we need jsoneditor.css on root?
- package.json
  - version is 2.1.0 now ?
  - why not use nyc anymore?
- actions.ts is registerRenderer/unregisterRenderer missing a dispatch? Add missing typings
- renderer.tsx why move protected methods to be utils?
- can't all services (dataservice, ruleservice, etc) replaced with actions
- testers.ts -> do we need isControl and is Scopable?
- json-forms.tsx 
  - why is schemaPromise public?
  - I support the TODO and only make the dispatch method public instead of the store
  - don't we need to clean stuff when the jsonforms elements is removed from the dom?
- reducers/common.ts -> can we type the code here?

## Generic Issues:
- define naming schema for variable eg uiSchema vs uischema
- add missing jsdoc for new methods

Missing the renderers will add further comments then

**Comment by eneufeld** [comment]
## Global State
I'm not sure whether we should remove the global state completely.
I think it would make sense to still support a global state, just like the one where all the default renderers are registered to. This allows the user to provide global renderers if there are multiple occurrences of jsonforms.
By removing the global state completely we would have to register all renderers multiple times.
I would prefer to keep a mix with the local state being more important.

**Comment by AhmetTanakol** [comment]
Clicking on a boolean control does not check the box. Only space bar is working on boolean controls

**Comment by edgarmueller** [comment]
Closing this now as follow-up issues have been created.
