### ISSUE TITLE
Several questions and possibly featurerequests

### ISSUE THREAD

**Issue by gentledepp** [eclipsesource/jsonforms#898]
Hello!
I went through the documentation of the latest jsonforms version for react and redux and came up with several issues:

1) from what I could see, that jsonforms has one state object in the redux store under the constant key "jsonforms" (http://jsonforms.io/docs/store)
but what happens, if I wanted to display mutliple forms simultaneously?
Is that supported at all=

2) for dropdown fields (just as an example) would it be possible to bind them to a REST endpoint? (like a dropdown to select a departmemt giving you a list of all existing departments) 
This could be very interesting combined with a filtered query as there may be so many departments, that I cannot just load them all into a local array.

3) allow for dependent form fields.
What I could see from the docs is, that it is possible to show a form field using a rule, whenever a previous field is answered.
For example: first we select the department, then another dropdown appears showing the list of members of the selected department.
3a) given that both dropdowns requrie a call to a rest service, is it possible to use the selected element of the department dropdown (the department id) as a parameter for the query of the member dropdown?
3b) now when I have selected a member, and then change the department, the selected member is not valid anymore as it depends on the department.
Now using jsonforms rules, the member dropdown would be hidden, but still contain the selected member.
What really should happen is, that the member dropdown is cleared as well!
Is that at all possible?

4) would it be possible to add validation which spans multiple fields?
and if so, maybe I would need to make an async call to the server to verify a field (e.g. make sure that the given username is unique). So is async validation supported at all? (or will it be in the future?

5) as you can add your own templates, do you think it would be feasible to create react native templates? I.e. use jsonforms in react native and generating a native UI for it?

Thank you so much for the clarifiaction!

**Comment by edgarmueller** [comment]
Hi,

thanks for your interest in JSON Forms! Regarding your questions:

1. The simplest approach would be to use different stores via react-redux's `Provider` (which we do on our website, for instance). Of course, that might not always be applicable, which is why I created issue #900, so we will try to look at it.
2. As we are primarily trying to focus on forms generation, there is no support for the described use case out-of-the-box. But for such occurrences, we provide the concept of a [custom control](http://jsonforms.io/docs/custom-renderers), where you can do more or less what you want and then register your renderer with JSON Forms. For the scenario you described an Autocomplete field which fetches its suggestions asynchronously from a server and binds against a string in the schema would probably make sense.
3. This is currently not possible, but it probably would be if a new kind of rule is introduced which would  also clear the contents of any currently hidden control (e.g. `SHOW_CLEAR` rule). If you think this is a good thing to have in JSONForms, please open an issue
4. Yes, in theory. We have open issues regarding these concerns, see [here](https://github.com/eclipsesource/jsonforms/issues/712) and [here](https://github.com/eclipsesource/jsonforms/issues/663), but currently there is no support yet.
5. Yes, absolutely. We couldn't yet try out JSON Forms with React Native, but from a conceptual point of view it would be a perfect fit. Basically you'd need to implement a new renderer set using React Native as we did with the material-ui renderer set. In our experience writing a new renderer set is quite manageable.   

 If you have any further questions, feel free to contact us, feedback is always welcome.

**Comment by edgarmueller** [comment]
@gentledepp Can we close this issue? Do you have any additional questions?
