### ISSUE TITLE
Handling of package-lock.json files

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#914]

**Comment by edgarmueller** [comment]
Moved to https://github.com/eclipsesource/jsonforms-react-seed/issues/10, closing this one.

**Comment by edgarmueller** [comment]
Re-opening due to recent MUI issues

**Comment by koegel** [comment]
IMHO this problem could be solved with the suggestion of Mat of committing the package lock json.

**Comment by edgarmueller** [comment]
It depends, note that the package-lock files are already commited and in use. Right now, the seed does not run if babel/runtime is not included as well, as the released version of MUI the 2.0.1 release is based is on, is missing in the dependencies. I think this is the result of not fixing the version constraints, since we often solve package-lock.json conflicts by just accepting one side of the conflict (because it's very tedious to properly merge those), which means that newer versions than the ones specified in the package.json could end up in the package-lock.json file.

I guess this issue is more about finding out how other libraries (not apps) handle the package.json and package-lock.json files.

**Comment by edgarmueller** [comment]
I've added a new section 'Developer documentation' that outlines the guidelines we aggred upon, see https://github.com/eclipsesource/jsonforms/wiki/Developer-documentation
