### ISSUE TITLE
Fetching data from an API

### ISSUE THREAD

**Issue by rohgoyal** [eclipsesource/jsonforms#951]
Hi, I was able to follow the tutorial to create UI based on my own JSON schema. 
import schema from './schema.json';
import uischema from './uischema.json';
import data from './data.json';

I am new to jsonforms so to React. 
My problem statement is to fetch the data by calling an API and then render. I followed this tutorial which explains how to call a REST API backend but from App.js
https://medium.freecodecamp.org/how-to-make-create-react-app-work-with-a-node-backend-api-7c5c48acb1b0

Because I need to declare data variable in index.js, I am not sure how to pass the data from App.js to index.js? Can someone help or suggest an alternate solution?

**Comment by edgarmueller** [comment]
Hi @rohgoyal, I'd connect the `App` component via `connect` (see [redux docs](https://github.com/reactjs/react-redux/blob/master/docs/api.md) for more info) to the store you've set up, so that you get access to the `dispatch` function. Then, in the `componentDidMount` function, once the promise has been resolved, you should be able to dispatch the `init` action again, but with the fetched data this time, such that it updates the data managed by JSONForms. Let me know if this helps

**Comment by edgarmueller** [comment]
@rohgoyal I'm closing this one for now, if you should have any questions or if something is unclear, please re-open.
