### ISSUE TITLE
Label renderer is broken

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#99]
The label renderer currently doesn't work.

**Comment by eneufeld** [comment]
didn't we decide to remove it?

**Comment by edgarmueller** [comment]
I don't know for sure, Stefan had another opinion than me, so I guess this is still up for discussion. In either case, we should then rename this issue.

**Comment by sdirix** [comment]
There could be use cases where a client wants to add textual information within the generated form where using groups and control-labels are not enough.

Probably there are not many of these cases and most of them could be worked around, but since the renderer is already implemented I would like to suggest to keep it anyway. However it should be renamed to TextRenderer or something similar.
