### ISSUE TITLE
Support for customizing option labels in enum renderer

### ISSUE THREAD

**Issue by danielclariondoor** [eclipsesource/jsonforms#990]
How do I create an enum with different value in the dropdown than I display?

**Comment by AnkurBegining** [comment]
@danielclariondoor You can create enum in your schema and populate it with different value. You can dynamically fill it too. You can import your schema and suppose your schema looks something like this

    {
        "type": "object",
         "properties": {
         "country": {
         "type": "string",
         "enum": ["First"]
          },
         "city": {
         "type": "string"
          }
       },
         "required": [
         "country", "language"
        ]
    } 

Then you can do it like `schema.properties.country.enum` and populate it.

**Comment by danielclariondoor** [comment]
Thanks for the response. I guess I wasn't clear what I'm asking.
I want to produce an html structure like this:
```
<select>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
```
wherein the value is different from the displayed option.

**Comment by edgarmueller** [comment]
@danielclariondoor Unfortunately this isn't' possible right now, since we'd first need to think of a good way how to customize this behavior (which I think makes sense). You could still create your own version of the EnumField renderer and, in your case, just capitalize the label and then override any default enum renderer. If you need help doing that, let me know, and I'll post an example (but let us know for which renderer set).

**Comment by sdirix** [comment]
This is now implemented with https://github.com/eclipsesource/jsonforms/pull/1591 for React/Material and will be part of the next release.

**Comment by JarnoRFB** [comment]
For anyone looking for this feature, it is documented here https://jsonforms.io/docs/labels#oneof-enum-titles.
