### ISSUE TITLE
Customizing the array layout

### ISSUE THREAD

**Issue by danielclariondoor** [eclipsesource/jsonforms#992]
Is it possible to specify the layout within an array?
I.e. I would like to use VerticalLayout and HorizontalLayout within the array?

**Comment by edgarmueller** [comment]
No, currently not, since it's hard-coded (it actually depends on the renderer set), but we'll add support for specifying an UI schema for an element within the array soon, which I think would solve your issue. This issue (support a separate UI schema for each element) popped up a few times by now, but we still haven't decided whether we wan't to support this via an additional option decoratively or use a separate UI schema registry similar to the renderer registry, or even both. We'll use this ticket to track this.

**Comment by eneufeld** [comment]
The Editor Package already has a ui schema registry: https://github.com/eclipsesource/jsonforms/blob/master/packages/editor/src/reducers/index.ts#L36
Maybe we should move this to the core?

**Comment by edgarmueller** [comment]
Right, thanks for pointing it out.

**Comment by edgarmueller** [comment]
Fixed via #1013 and released with 2.0.2. You can find some documentation about this in the [Providing UI schemas](https://jsonforms.io/docs/providing-uischemas) section. If you should have any additional questions/issues, let us know.
